### PR TITLE
Populate ResponseContentPreview when creating a WebServiceException from an AutoWebServiceResponse.

### PR DESCRIPTION
**Pull request by Auk14HP**

### CODE REVIEW

**Review by ejball — APPROVED** [review]

**Review by dustinsoftware — APPROVED** [review]

**Comment by Auk14HP** [comment]
Could you merge this if it still looks good, @ejball?

**Comment by Auk14HP** [comment]
Do I need to go and fix all of the errors listed in this run that failed?

https://github.com/Faithlife/FaithlifeWebRequests/actions/runs/1136936925

At a glance they don't look related to my change.

**Comment by ejball** [comment]
I fixed them.

**Pull request merged**
